{{- if .Values.jenkins.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: {{ .Values.jenkins.namespace }}
    server: {{ .Values.argocd.cluster }}
  project: {{ .Values.argocd.project }}
  source:
    chart: jenkins
    helm:
      values: |-
{{ .Values.jenkins.values | indent 8 }}
      valueFiles:
      - values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.jenkins.version }}
{{- end }}
